language: python
python:
  - "2.6"
  - "2.7"

install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -e . --use-mirrors"
  - "pip install baidupcs"

script:
  - "python -m compileall -f ."
  - "python setup.py test"
  - "py.test"

notifications:
  email: false
